title: THETAI
description: © 2023  THETAI. ALL RIGHTS RESERVED.
theme: just-the-docs

logo: "/assets/images/logo.jpg"

# url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
